services:
  db:
    image: postgres:14.5
    environment:
      POSTGRES_USER: practicalEdges
      POSTGRES_PASSWORD: pe09
      POSTGRES_DB: placement
    ports:
      - "5432:5432"
    volumes:
      - ./data-pg-practicaledges/db:/var/lib/postgresql/data